repos:
  - repo: local
    hooks:
      - id: format
        stages: [commit]
        name: format
        entry: pdm
        args: ["run", "format"]
        language: system
        types: [python]
        pass_filenames: false

      - id: fix_format
        stages: [push]
        name: fix_format
        entry: pdm
        args: ["run", "fix_format"]
        language: system
        types: [python]
        pass_filenames: false

      - id: lint
        stages: [push]
        name: lint
        entry: pdm
        args: ["run", "lint"]
        language: system
        types: [python]
        pass_filenames: false

      - id: type
        stages: [push]
        name: type
        entry: pdm
        args: ["run", "type"]
        language: system
        types: [python]
        pass_filenames: false

      - id: test
        stages: [push]
        name: test
        entry: pdm
        args: ["run", "test"]
        language: system
        types: [python]
        pass_filenames: false
