# This is a draft! The project currently uses setup.py.

[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools"
]

[tool.poetry]
name = "ipyvizzu"
version = "0.15.0"
description = "Build animated charts in Jupyter Notebook and similar environments with a simple Python syntax"
license = "Apache-2.0"
authors = ["Vizzu Inc. <hello@vizzuhq.com>"]
readme = "README.md"
repository = "https://github.com/vizzuhq/ipyvizzu"
documentation = "https://ipyvizzu.vizzuhq.com"
keywords = [
    "python",
    "chart",
    "charts",
    "dataviz",
    "jupyter",
    "animation",
    "ipython",
    "graphs",
    "storytelling",
    "jupyter-notebook",
    "data-visualization",
    "graphing",
    "plotting",
    "charting",
    "vizzu"
]
packages = [{ include = "ipyvizzu", from = "src/ipyvizzu" }, { include = "ipyvizzu.integrations" }]
classifiers = [
    "Environment :: Console",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3"
]

[tool.poetry.dependencies]
IPython = "^7.31.0"
jsonschema = "^4.0.1"
pandas = { version = "^1.2.1", python = "^3.8" }
python = "^3.7"
fugue = { version = "^0.8.1", python = "^3.7", optional = true}

[tool.poetry.extras]
extras = ["fugue"]

[tool.poetry.urls]
"Tracker" = "https://github.com/vizzuhq/ipyvizzu/issues"
