name: CI

on:
  workflow_call:

jobs:

  check_ci:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Cache repo
      uses: actions/cache@v3
      with:
        path: |
          ./*
          !.git
        key: ipyvizzu-${{ github.run_id }}

    - name: Cache coverage
      uses: actions/cache@v3
      with:
        path: ./tests/coverage
        key: ipyvizzu-coverage-${{ github.run_id }}

    - name: Touch dev environment
      run: make touch-dev

    - name: Touch dev-js environment
      run: make touch-dev-js
          
    - name: Check format
      run: make check-format

    - name: Check lint
      run: make check-lint

    - name: Check typing
      run: make check-typing

    - name: Run test
      run: make test

    - name: Check js
      run: make check-js
