name: CI

on:
  workflow_call:

jobs:
  check_ci_src:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Cache dev-py environment
        uses: actions/cache@v3
        with:
          path: .venv
          key: dev-py-${{ hashFiles('pdm.lock') }}

      - name: Cache dev-js environment
        uses: actions/cache@v3
        with:
          path: node_modules
          key: dev-js-${{ hashFiles('package-lock.json') }}

      - name: Format
        run: |
          source .venv/bin/activate
          pdm run format_src

      - name: Lint
        run: |
          source .venv/bin/activate
          pdm run lint_src

      - name: Type
        run: |
          source .venv/bin/activate
          pdm run type_src

      - name: Test
        run: |
          source .venv/bin/activate
          pdm run test

      - name: Cache coverage
        uses: actions/cache@v3
        with:
          path: ./.tox/py310/coverage
          key: coverage-${{ github.run_id }}

  check_ci_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Cache dev-py environment
        uses: actions/cache@v3
        with:
          path: .venv
          key: dev-py-${{ hashFiles('pdm.lock') }}

      - name: Cache dev-js environment
        uses: actions/cache@v3
        with:
          path: node_modules
          key: dev-js-${{ hashFiles('package-lock.json') }}

      - name: Format
        run: |
          source .venv/bin/activate
          pdm run format_docs

      - name: Lint
        run: |
          source .venv/bin/activate
          pdm run lint_docs

  check_ci_tools:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Cache dev-py environment
        uses: actions/cache@v3
        with:
          path: .venv
          key: dev-py-${{ hashFiles('pdm.lock') }}

      - name: Cache dev-js environment
        uses: actions/cache@v3
        with:
          path: node_modules
          key: dev-js-${{ hashFiles('package-lock.json') }}

      - name: Format
        run: |
          source .venv/bin/activate
          pdm run format_tools

      - name: Lint
        run: |
          source .venv/bin/activate
          pdm run lint_tools

      - name: Type
        run: |
          source .venv/bin/activate
          pdm run type_tools
