name: Build documentation

on:
  workflow_call:

jobs:
  build_doc:

    runs-on: ubuntu-latest

    env:
      PUPPETEER_CACHE_DIR: ${{ github.workspace }}/node_modules/.chromium

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ./.venv_ipyvizzu
          key: venv-ipyvizzu-${{ github.run_id }}

      - uses: actions/cache@v3
        with:
          path: ./node_modules
          key: nodemodules-ipyvizzu-${{ github.run_id }}

      - uses: actions/cache@v3
        with:
          path: ./tests/coverage
          key: coverage-ipyvizzu-${{ github.run_id }}

      - name: Touch dev environment
        run: make touch-dev

      - name: Touch dev-js environment
        run: make touch-dev-js

      - name: Set Jupyter kernel
        run: make install-kernel

      - name: Checkout vizzu-lib
        uses: actions/checkout@v2
        with:
          repository: vizzuhq/vizzu-lib
          path: vizzu-lib

      - name: Build documentation
        run: make doc
