name: Release

on:
  workflow_call:

jobs:

  release_package:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: ./.venv_ipyvizzu
        key: venv-ipyvizzu-${{ github.run_id }}

    - name: Touch dev environment
      run: make touch-dev

    - name: Build package
      run: make release-wo-restore

    - name: Release package
      run: ./.venv_ipyvizzu/bin/python -m twine upload -u "__token__" -p "${{ secrets.PYPI_API_TOKEN }}" dist/*.tar.gz  dist/*.whl
      if: ( github.event_name == 'release' && github.event.action == 'published' )
    
    - name: Upload package
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
        gh release upload ${{ github.event.release.tag_name }} dist/*.tar.gz  dist/*.whl --clobber
      if: ( github.event_name == 'release' && github.event.action == 'published' )
